services:
  - type: web
    name: cv-software
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libreoffice
      pip install -r requirements.txt
    startCommand: "gunicorn app:app"
    plan: free
    branch: main
    autoDeploy: true
