services:
  - type: web
    name: cv-software
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: "gunicorn app:app"
    plan: free
    branch: main
    autoDeploy: true
